apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: reloader
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/Sachaa-Thanasius/iac.git
        revision: HEAD
        directories:
          - path: reloader/*
  template:
    metadata:
      name: "reloader-{{path.basename}}"
    spec:
      project: default
      sources:
        - repoURL: https://github.com/Sachaa-Thanasius/iac.git
          targetRevision: HEAD
          ref: values
        - chart: reloader
          repoURL: https://stakater.github.io/stakater-charts/
          targetRevision: "2.1.5"
          helm:
            valueFiles:
              - "$values/reloader/{{path.basename}}/values.yaml"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}"
      syncPolicy:
        automated:
          prune: true
