apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: reloader
spec:
  generators:
    - git:
        repoURL: https://github.com/Sachaa-Thanasius/iac.git
        revision: HEAD
        directories:
          - path: reloader/*
  template:
    metadata:
      name: "reloader-{{path.basename}}"
    spec:
      project: "{{path.basename}}"
      sources:
        - repoURL: https://github.com/Sachaa-Thanasius/iac.git
          targetRevision: HEAD
          ref: values
        - chart: reloader
          repoURL: https://stakater.github.io/stakater-charts/
          revision: latest
          helm:
            valueFiles:
              - '$values/reloader/{{path.basename}}/values.yaml'
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}"
      syncPolicy:
        automated:
          prune: true
